Repository beyond-SW-Camp-14th-clover/be14-4th-clover-moodiary-BE, pull requests merged in 2025-04, with the labels that each got.

#4 docs : refactor 템플릿 생성
  .github/ISSUE_TEMPLATE/feature-템플릿.md
  .github/ISSUE_TEMPLATE/hotfix-템플릿.md
  .github/ISSUE_TEMPLATE/refactor-템플릿.md
Labels: documentation

#5 [Feat] 추천 행동 도메인 관련 테이블 생성 및 더미 데이터 초안
  db/action/CreateActionTable.sql
  db/action/InsertActionDummy.sql
Labels: enhancement

#7 feat : pr 템플릿 생성
  .github/PULL_REQUEST_TEMPLATE/pr_template
Labels: documentation

#9 [Feat] 전체 테이블 생성 쿼리
  db/all/CreateAllTables.sql
Labels: enhancement

#10 docs : gitignore 설정
  .gitignore
Labels: documentation

#14 [Feature] 유저 아이디 찾기 , 정보 조회 기능 추가
  moodiary/build.gradle
  moodiary/src/main/java/com/clover/moodiary/user/command/contorller/UserCommandController.java
  moodiary/src/main/java/com/clover/moodiary/user/command/entity/UserEntity.java
  moodiary/src/main/java/com/clover/moodiary/user/command/repository/UserCommandRepository.java
  moodiary/src/main/java/com/clover/moodiary/user/command/service/UserCommandService.java
  moodiary/src/main/java/com/clover/moodiary/user/command/service/UserCommandServiceImpl.java
  moodiary/src/main/java/com/clover/moodiary/user/query/controller/UserController.java
  moodiary/src/main/java/com/clover/moodiary/user/query/dto/RequestEmailDTO.java
  moodiary/src/main/java/com/clover/moodiary/user/query/dto/UserDTO.java
  moodiary/src/main/java/com/clover/moodiary/user/query/service/UserServiceImpl.java
  moodiary/src/main/resources/com/clover/moodiary/user/query/mapper/UserMapper.xml
Labels: enhancement

#15 [Feat] 스티커,사진 관련 DB수정
  db/all/CreateAllTables.sql
Labels: enhancement

#16 DB 패키지 정리 & 더미 데이터
  db/CreateAllTables.sql
  db/DummyAll.sql
  db/action/CreateActionTable.sql
  db/action/InsertActionDummy.sql
  db/diary/CreateTables.sql
  db/diary/DDL/DDL.sql
  db/diary/DUMMY/pet.sql
  db/diary/DUMMY/register_questions.sql
  db/diary/DUMMY/user.sql
Labels: enhancement

#18 [Feat] action / 회원 가중치 초기화 기능 추가
  moodiary/src/main/java/com/clover/moodiary/action/command/application/controller/CommandActionController.java
  moodiary/src/main/java/com/clover/moodiary/action/command/application/dto/ActionTagDTO.java
  moodiary/src/main/java/com/clover/moodiary/action/command/application/dto/UserPreferencesDTO.java
  moodiary/src/main/java/com/clover/moodiary/action/command/application/service/CommandActionService.java
  moodiary/src/main/java/com/clover/moodiary/action/command/application/service/CommandActionServiceImpl.java
  moodiary/src/main/java/com/clover/moodiary/action/command/domain/aggregate/entity/UserPreferences.java
  moodiary/src/main/java/com/clover/moodiary/action/command/domain/aggregate/entity/UserPreferencesPK.java
  moodiary/src/main/java/com/clover/moodiary/action/command/domain/repository/UserPreferencesRepository.java
  moodiary/src/main/java/com/clover/moodiary/action/query/controller/ActionController.java
  moodiary/src/main/java/com/clover/moodiary/action/query/mapper/ActionMapper.java
  moodiary/src/main/java/com/clover/moodiary/action/query/service/ActionService.java
  moodiary/src/main/java/com/clover/moodiary/action/query/service/ActionServiceImpl.java
  moodiary/src/main/resources/com/clover/moodiary/action/query/mapper/ActionMapper.xml
  moodiary/src/test/java/com/clover/moodiary/action/InsertInitialUserPreferencesTest.java
Labels: enhancement

#19 DB 감정 분석 테이블 수정
  db/CreateAllTables.sql
Labels: enhancement

#23 [Feat] 추천 행동 관련 더미 데이터
  db/DummyAll.sql
Labels: enhancement

#24 [HotFix] User 도메인 실행되게 수정
  moodiary/src/main/java/com/clover/moodiary/user/command/controller/UserCommandController.java
  moodiary/src/main/java/com/clover/moodiary/user/command/service/UserCommandService.java
  moodiary/src/main/java/com/clover/moodiary/user/command/service/UserCommandServiceImpl.java
Labels: bug

#21 [Feat] 추천 행동 관련 알고리즘 진행중 1
  moodiary/src/main/java/com/clover/moodiary/MoodiaryApplication.java
  moodiary/src/main/java/com/clover/moodiary/action/command/application/controller/CommandActionController.java
  moodiary/src/main/java/com/clover/moodiary/action/command/application/dto/RecommendedActionDTO.java
  moodiary/src/main/java/com/clover/moodiary/action/command/application/dto/TaggedRecommendedActionsDTO.java
  moodiary/src/main/java/com/clover/moodiary/action/command/application/service/CommandActionService.java
  moodiary/src/main/java/com/clover/moodiary/action/command/application/service/CommandActionServiceImpl.java
  moodiary/src/main/java/com/clover/moodiary/action/query/controller/ActionController.java
  moodiary/src/main/java/com/clover/moodiary/action/query/mapper/ActionMapper.java
  moodiary/src/main/java/com/clover/moodiary/action/query/service/ActionService.java
  moodiary/src/main/java/com/clover/moodiary/action/query/service/ActionServiceImpl.java
  moodiary/src/main/resources/com/clover/moodiary/action/query/mapper/ActionMapper.xml
Labels: enhancement

#29 [Feat] 추천 행동 마무리
  moodiary/src/main/java/com/clover/moodiary/action/command/application/controller/CommandActionController.java
  moodiary/src/main/java/com/clover/moodiary/action/command/application/service/CommandActionService.java
  moodiary/src/main/java/com/clover/moodiary/action/command/application/service/CommandActionServiceImpl.java
  moodiary/src/main/java/com/clover/moodiary/action/query/controller/ActionController.java
  moodiary/src/main/java/com/clover/moodiary/action/query/mapper/ActionMapper.java
  moodiary/src/main/java/com/clover/moodiary/action/query/service/ActionService.java
  moodiary/src/main/java/com/clover/moodiary/action/query/service/ActionServiceImpl.java
  moodiary/src/main/resources/com/clover/moodiary/action/query/mapper/ActionMapper.xml
Labels: enhancement

#30 유저 도메인 기능 추가
  .gitignore
  db/CreateAllTables.sql
  moodiary/build.gradle
  moodiary/src/main/java/com/clover/moodiary/user/command/config/JwtProperties.java
  moodiary/src/main/java/com/clover/moodiary/user/command/config/SecurityConfig.java
  moodiary/src/main/java/com/clover/moodiary/user/command/controller/UserCommandController.java
  moodiary/src/main/java/com/clover/moodiary/user/command/dto/LoginRequest.java
  moodiary/src/main/java/com/clover/moodiary/user/command/dto/LoginResponse.java
  moodiary/src/main/java/com/clover/moodiary/user/command/dto/PasswordReset.java
  moodiary/src/main/java/com/clover/moodiary/user/command/dto/PasswordResetRequest.java
  moodiary/src/main/java/com/clover/moodiary/user/command/dto/RegisterRequest.java
  moodiary/src/main/java/com/clover/moodiary/user/command/dto/UpdateUserRequest.java
  moodiary/src/main/java/com/clover/moodiary/user/command/entity/PasswordResetToken.java
  moodiary/src/main/java/com/clover/moodiary/user/command/entity/RegisterQuestion.java
  moodiary/src/main/java/com/clover/moodiary/user/command/entity/User.java
  moodiary/src/main/java/com/clover/moodiary/user/command/entity/UserEntity.java
  moodiary/src/main/java/com/clover/moodiary/user/command/repository/PasswordResetTokenRepository.java
  moodiary/src/main/java/com/clover/moodiary/user/command/repository/RegisterQuestionRepository.java
  moodiary/src/main/java/com/clover/moodiary/user/command/repository/UserCommandRepository.java
  moodiary/src/main/java/com/clover/moodiary/user/command/repository/UserRepository.java
  moodiary/src/main/java/com/clover/moodiary/user/command/service/UserCommandService.java
  moodiary/src/main/java/com/clover/moodiary/user/command/service/UserCommandServiceImpl.java
  moodiary/src/main/java/com/clover/moodiary/user/command/util/BooleanYNConverter.java
  moodiary/src/main/java/com/clover/moodiary/user/command/util/JwtUtil.java
  moodiary/src/main/java/com/clover/moodiary/user/command/util/MailUtil.java
  moodiary/src/main/java/com/clover/moodiary/user/query/controller/UserController.java
Labels: enhancement

#37 feat: Cors 설정 추가
  moodiary/src/main/java/com/clover/moodiary/user/command/config/WebConfig.java
Labels: enhancement

#46 Feature : 인증 인가 설정 및 jwt 토큰 pk값 파싱
  moodiary/src/main/java/com/clover/moodiary/user/command/config/SecurityConfig.java
  moodiary/src/main/java/com/clover/moodiary/user/command/security/JwtAuthenticationFilter.java
  moodiary/src/main/java/com/clover/moodiary/user/query/controller/UserController.java
Labels: enhancement

#48 [Refactor] action / 추천 행동 도메인 userId 얻는 방식 변경
  moodiary/src/main/java/com/clover/moodiary/action/command/application/controller/CommandActionController.java
  moodiary/src/main/java/com/clover/moodiary/action/query/controller/ActionController.java
Labels: enhancement

#51 [Feat] 공유 일기 테스트 케이스, 조회 부분 수정
  moodiary/src/main/java/com/clover/moodiary/shareddiary/command/dto/CreateSharedDiaryRequest.java
  moodiary/src/main/java/com/clover/moodiary/shareddiary/command/dto/DeleteSharedDiaryRequest.java
  moodiary/src/main/java/com/clover/moodiary/shareddiary/command/dto/UpdateSharedDiaryRequest.java
  moodiary/src/main/java/com/clover/moodiary/shareddiaryroom/command/dto/CreateSharedDiaryRoomRequest.java
  moodiary/src/main/java/com/clover/moodiary/shareddiaryroom/command/dto/EnterSharedDiaryRoomRequest.java
  moodiary/src/main/java/com/clover/moodiary/shareddiaryroom/query/dto/SharedDiaryRoomResponse.java
  moodiary/src/main/resources/com/clover/moodiary/shareddiaryroom/query/mapper/SharedDiaryRoomMapper.xml
  moodiary/src/test/java/com/clover/moodiary/shareddiaryroom/command/SharedDiaryRoomCommandServiceTest.java
  moodiary/src/test/java/com/clover/moodiary/shareddiay/command/SharedDiaryCommandServiceTest.java
Labels: enhancement
